remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme

title: Euro-RV — European Workshop on Hardware-Software Co-Design for Future RISC-V Architectures
subtitle: October 31 / November 1, 2026, Athens, Greece. Co-located @ MICRO 2026

description: Euro-RV @ MICRO 2026
